### ISSUE TITLE
context attribute srcDir always required, but undocumented

### ISSUE THREAD

**Issue by daxim** [jsoverson/preprocess#43]
The program

    var fs = require('fs');
    var pp = require('preprocess');

    pp.preprocess(
        fs.readFileSync('example.js', { encoding : 'UTF-8' }),
        {},
        'js'
    );

throws the exception

    TypeError: Arguments to path.join must be strings
        at path.js:360:15
        at Array.filter (native)
        at Object.exports.join (path.js:358:36)
        at ./node_modules/preprocess/lib/preprocess.js:63:32
        at String.replace (native)
        at Object.preprocess (./node_modules/preprocess/lib/preprocess.js:59:11)
        at Object.<anonymous> (./bug.js:4:4)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)

The problem is that the second parameter to `preprocess`, the context object, is expected to have a key `srcDir` and a path part value, e.g. `{ srcDir: '.' }` works. This is documented nowhere.

**Comment by BendingBender** [comment]
fixed in 506dd7582c
